CSYS 301 TagDropdown
labcodes/confetti-ds pull request #22
Opened 2022-04-01 00:59 UTC by ddevdan

**Context**
[Task](https://labcodes.atlassian.net/browse/CSYS-301)
[Figma](https://www.figma.com/file/Wx7jj5klQn3YsRA2XcIV3E/Confetti-%2F-%F0%9F%93%9A-Components?node-id=8933%3A3153)

**Description**
This PR creates TagDropdown component to Confetti DS

Screenshots

https://user-images.githubusercontent.com/42525687/161174063-72905ef2-8896-4b2a-8932-48da96c18daa.mp4

2022-04-01 20:54 UTC, lucianoratamero requested changes
Sei que parece muita coisa, mas o código tá BEM BOM.
Pode ser que eu tenha viajado em algum comentário, então se algo não fizer sentido, traz pra nossa reunião de quinta que vem, ok?

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.js
> +    dropdownType: PropTypes.oneOf(dropdownOptions.types).isRequired,
A gente já tem o dropdown de botão implementado?
Se não, na próxima vez que fizer algo assim, é preferível que essa opção nem exista, pra não gerar confusão entre o código diz que suporta e o que é efetivamente suportado.
Mas precisa mudar não, tá de boas. Provalvelmente você vai fazer o de botão logo em seguida mesmo ;]

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.js
> +  expectedKeys = {
Se todos são true, isso tem mais cara de ser um array do que um objeto.
Você só teria que mudar a implementação da busca por expectedKey no evento de keyup.

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.js
> +    const notExpectedKey = !expectedKeys[key];
Aqui que teria que mudar caso expectedKeys fosse um array.
Você poderia usar um `expectedKeys.includes(key)`, por exemplo.

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.js
> +    if (isEsc) {
Acho que faltou aquela refatoração pra simplificar esses dois casos de if, né?

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.js
> +  */
Perfeito! Adorei a documentação :]

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.js
> +            // change it to || child.type == OptionItem...
O Daniel do futuro vai adorar esse comentário!

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.test.js
> +    expect(wrapper.state().isOpen).toBe(true);
Faltou refatorar esse teste pra não checar o state diretamente, como você fez nos outros.

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.test.js
> +    const expectedValues = [
Gostei do jeito que você conseguiu introduzir aleatoriedade reprodutível nesse teste :sparkles:

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.test.js
> +    // expect(wrapper.state().selected).toStrictEqual({ ref: null, index: null });
Opa, olha o código comentado!
Recomendo sempre limpar código comentado dos commits finais.
Tem como tirar ele daqui?

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.test.js
> +    // wrapper.parent().text();
Código comentado aqui também

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/AbstractDropdown.test.js
> +  it("calls props.onClose and props.onOpen when clicked or blured", async () => {
Esse teste não cobre o cenário de blur. Seria bom adicionar esse cenário nesse teste ou separar o caso de blur em outro teste.

2022-04-01 20:54 UTC, lucianoratamero commented on src/Dropdown/DropdownOption.js
> +    /** This function fires when user select a valid option */
Mesmos typos do AbstractDropdown

2022-04-01 20:54 UTC, lucianoratamero commented on src/Tags/AbstractTag.js
> +        tabIndex={tabIndex}
O problema de colocarmos tabIndex com default de 0 nesse componente é que isso torna todos os componentes de tag acessíveis por navegação de teclado, quando muitas vezes eles são apenas elementos visuais não-interativos (como documentado aqui: https://webaim.org/techniques/keyboard/tabindex).

É preferível que o default dele seja undefined, e que, caso ele seja undefined, a prop de tabIndex sequer seja passada para esse elemento.

A maneira com que fazemos isso é a mesma para os atributos `disabled` dos inputs e botões.
Esse aqui é um exemplo bom: https://github.com/labcodes/confetti-ds/blob/main/src/Input/AbstractTextInput.js#L216

2022-04-01 20:54 UTC, lucianoratamero commented on src/Tags/DropdownTag.js
> +    tabIndex: PropTypes.string,
Na minha opinião, esse componente, por ser interativo, sempre vai ter que passar tabIndex como 0 pra dentro, então não acho necessário que o usuário possa passar um tabIndex customizado.
Não temos ainda um caso em que isso seja útil, e isso pode introduzir problemas de acessibilidade, caso o usuário passe -1, por exemplo.
Minha recomendação é tirar o tabIndex das props desse componente, mas manter ele passando `tabIndex={0}` pra tag abstrata.

2022-04-01 22:52 UTC, ddevdan commented on src/Dropdown/AbstractDropdown.js
> +    if (isEsc) {
A logica deles é diferente.

Eu uso o isClosed pra fazer uma acao antes de abrir o dropdown, dessa forma eu consigo apenas abrir o dropdown sem mover o foco pra a proxima opcao. 

Se eu colocar o (isEsc || isClosed) o isEsc passa a abrir o dropdown quando ele ta fechado. E não é interessante que isso ocorra pq a funcao da tecla Esc é a de apenas fechar o dropdown.

2022-04-01 22:54 UTC, ddevdan commented on src/Dropdown/AbstractDropdown.js
> +  */
![download](https://user-images.githubusercontent.com/42525687/161352021-91719027-0b9a-43da-a1cd-16f84cc89b7a.gif)

2022-04-01 22:55 UTC, ddevdan commented on src/Dropdown/AbstractDropdown.js
> +  */
![tumblr_mbacmmyJN71qmypdq540 (1)](https://user-images.githubusercontent.com/42525687/161352096-ab082e57-4690-48f9-8374-e7ea3844abc1.gif)

2022-04-01 22:55 UTC, ddevdan commented on src/Dropdown/AbstractDropdown.js
> +            // change it to || child.type == OptionItem...
kkkkkkkk

2022-04-01 23:00 UTC, ddevdan commented on src/Dropdown/AbstractDropdown.test.js
> +    const expectedValues = [
![tumblr_mbacy8lpqN1qmypdq540](https://user-images.githubusercontent.com/42525687/161352412-3010dc26-7c3e-4f6c-81e0-785529933115.gif)

2022-04-04 18:03 UTC, ddevdan commented on src/Tags/DropdownTag.js
> +    tabIndex: PropTypes.string,
Eu preciso dessa prop para sobrepor o tabindex inicial do `DropdownTag` pelo do `.lab-dropdown__invisible-button`. Se eu não passar ela, o foco do tab vai primeiro pro   `.lab-dropdown__invisible-button` e depois pro `DropdownTag`, o que atrapalha a navegação pelo keyboard. 

Resolvi isso criando um componente que herda o `DropdownTag` (`TagDropdownTrigger`) pra ser usado exclusivamente no componente que estamos criando.

2022-04-14 19:11 UTC, lucianoratamero approved these changes
LGTM :rocket:

2022-04-21 20:16 UTC, merged