[CSYS-355 Migrating Alert component]
labcodes/confetti-ds pull request #43
Opened 2022-08-15 19:10 UTC by tiidadavena

Link to task:
[CSYS-355](https://labcodes.atlassian.net/browse/CSYS-355)

Staging app: https://CSYS-355-migrate-alert--confetti-storybook.netlify.app/

How to test:
After running your project locally, run the `Alert.test.js`to check if the Alert component is working as expected.

Description of your solution:

Removing previous mentions from Class Components and moving the Props outside the functional component scope.

Screenshots (when applicable):

2022-08-27 03:08 UTC, lucianoratamero requested changes

2022-08-27 03:08 UTC, lucianoratamero commented on src/Alert.js
> +  const handleIcon = () =>
instead of handleIcon, I'd go with renderIcon. same for the other functions that return a component.

or you coult inline with a ternary too.

2022-08-30 20:32 UTC, tiidadavena commented on src/Alert.js
> +  const handleIcon = () =>
I really liked the ternary suggestion, so I jumped into that approach 💯

2022-09-02 16:16 UTC, lucianoratamero approved these changes

2022-09-06 14:15 UTC, merged