CSYS-210: Migrate Tags
labcodes/confetti-ds pull request #5
Opened 2021-02-09 22:28 UTC by CavalcanteLucas

**Related to:**
https://github.com/labcodes/confetti-storybook/pull/12

**Link to task:**
https://labcodes.atlassian.net/browse/CSYS-210

**Staging app:**
https://migrate-tag--labstorybook-master.netlify.app/

**How to test:**
Access the staging app. Go to the `Tags` sections. Try different combinations of colors, skins, icons.

**Description of your solution:**
This PR refactor the type of some props in `Tags` so they become selectable. The `constant` file is enhanced with `TAG_COLORS`.

An empty string options is required for `icon` and `color` props because of how they are initialilized. 
The initialization of `color` could be modified to match the `AbstractTag` default ("mineral"). But that would require further refactorings with the CSS of `Tags`.

2021-02-10 19:34 UTC, lucianoratamero requested changes

2021-02-10 19:34 UTC, lucianoratamero commented on src/Tags/DropdownTag.js
> +    icon: PropTypes.oneOf(["", ...ICON_TYPES]),
as we discussed previously, `""` shouldn't be an option in our source code.
you'll probably have to remove this everywhere and use the constants directly.

2021-02-10 23:33 UTC, CavalcanteLucas commented on src/Tags/DropdownTag.js
> +    icon: PropTypes.oneOf(["", ...ICON_TYPES]),
I was referring to add `""` as an option to the storybook actually.

In this case, removing this from one of the options would require major refactorings.
For the `color` case that'd be easier, since `AbstractTag` uses "mineral" as default, albeit that'd require changes in the CSS structure (and in tests).
For the `icon` case, I can't think how that'd could work. Removing the `""` case would mean that there couldn't be `Tags` without icons - in other words, `Tags` would always have icons. Which would mean we couldn't ever use `thumbs` for example etc.

2021-02-13 04:49 UTC, CavalcanteLucas commented on src/Tags/DropdownTag.js
> +    icon: PropTypes.oneOf(["", ...ICON_TYPES]),
fixed

2021-02-18 18:39 UTC, lucianoratamero approved these changes
:trophy:

2021-02-18 18:54 UTC, merged