Enhance 'icon' and 'thumbSrc' prop description of 'Tags'
labcodes/confetti-ds pull request #8
Opened 2021-02-22 23:03 UTC by CavalcanteLucas

**Link to task:**
https://labcodes.atlassian.net/browse/CSYS-210

**Staging app:**
https://migrate-tag-qa--confetti-storybook.netlify.app/

**How to test:**
Access to the staging app, go to the documentation of the stories for Tags and check if their new description are in accordance with expected.

**Description of your solution:**
This PR enhance the prop description of `Tags` to make clear that `icon` and `thumbSrc` props cannot be filled simultaneously.

2021-02-23 19:27 UTC, falconedani approved these changes
🏆

2021-02-23 19:28 UTC, falconedani requested changes
Missing:

In confetti-ds change default props for icon and color to undefined, and remove "" from oneOf available options.

2021-02-24 16:29 UTC, CavalcanteLucas commented
> Missing:
> 
> In confetti-ds change default props for icon and color to undefined, and remove "" from oneOf available options.

I don't understand.
Can't find any concrete `Tag` component where `icon` or `color` defaultProp is not set to `undefined`. 
Also, can't find any place where `""` is one of the options for those props. 

```
➜  Tags git:(migrate-tag-qa) ls                       
AbstractTag.js       DropdownTag.test.js  RemovableTag.test.js  __snapshots__
AbstractTag.test.js  index.js             SimpleTag.js          TogglableTag.js
DropdownTag.js       RemovableTag.js      SimpleTag.test.js     TogglableTag.test.js
➜  Tags git:(migrate-tag-qa) grep -e "oneOf" -r .
./SimpleTag.js:    icon: PropTypes.oneOf(ICON_TYPES),
./SimpleTag.js:    color: PropTypes.oneOf(TAG_COLORS),
./SimpleTag.js:    skin: PropTypes.oneOf(["pale", "vivid"]),
./DropdownTag.js:    icon: PropTypes.oneOf(ICON_TYPES),
./DropdownTag.js:    color: PropTypes.oneOf(TAG_COLORS),
./DropdownTag.js:    skin: PropTypes.oneOf(["pale", "vivid"]),
./TogglableTag.js:    color: PropTypes.oneOf(TAG_COLORS),
./RemovableTag.js:    icon: PropTypes.oneOf(ICON_TYPES),
./RemovableTag.js:    color: PropTypes.oneOf(TAG_COLORS),
./RemovableTag.js:    skin: PropTypes.oneOf(["pale", "vivid"]),
```

2021-02-25 12:08 UTC, falconedani approved these changes
LGTM!

2021-02-25 15:36 UTC, merged